"""Add soft delete columns to users and projects

Revision ID: b622088c983f
Revises: 759f742cf9d5
Create Date: 2026-06-09 09:12:36.711895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b622088c983f'
down_revision: Union[str, None] = '759f742cf9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'deleted_at')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_column('projects', 'is_deleted')
    op.drop_column('projects', 'deleted_at')
    # ### end Alembic commands ###
