"""Initial baseline with indexes

Revision ID: ca8dea5846eb
Revises: 
Create Date: 2026-06-08 17:37:14.849594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8dea5846eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('admin', 'org_manager', 'engineer', name='userrole'), nullable=False),
    sa.Column('organization', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('topology', sa.String(length=64), nullable=False),
    sa.Column('num_qubits', sa.Integer(), nullable=False),
    sa.Column('target_frequency_ghz', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'review', 'completed', name='projectstatus'), nullable=False),
    sa.Column('substrate_material', sa.String(length=64), nullable=False),
    sa.Column('metal_layer', sa.String(length=64), nullable=False),
    sa.Column('design_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_topology'), 'projects', ['topology'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_created_at'), 'chat_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_history_project_id'), 'chat_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_table('layouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_tag', sa.String(length=64), nullable=False),
    sa.Column('placement_json', sa.JSON(), nullable=False),
    sa.Column('gds_content', sa.Text(), nullable=True),
    sa.Column('qiskit_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layouts_project_id'), 'layouts', ['project_id'], unique=False)
    op.create_table('qclang_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ast_json', sa.JSON(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qclang_files_project_id'), 'qclang_files', ['project_id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('solver', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='simulationstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('runtime_seconds', sa.Float(), nullable=True),
    sa.Column('memory_gb', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_created_at'), 'simulations', ['created_at'], unique=False)
    op.create_index(op.f('ix_simulations_project_id'), 'simulations', ['project_id'], unique=False)
    op.create_index(op.f('ix_simulations_status'), 'simulations', ['status'], unique=False)
    op.create_table('tapeout_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_tag', sa.String(length=64), nullable=False),
    sa.Column('gds_content', sa.Text(), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('fab_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tapeout_packages_project_id'), 'tapeout_packages', ['project_id'], unique=False)
    op.create_index(op.f('ix_tapeout_packages_version_tag'), 'tapeout_packages', ['version_tag'], unique=False)
    op.create_table('verification_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'passed', 'failed', 'warning', name='verificationstatus'), nullable=False),
    sa.Column('drc_passed', sa.Boolean(), nullable=False),
    sa.Column('violations', sa.JSON(), nullable=False),
    sa.Column('frequency_collisions', sa.JSON(), nullable=False),
    sa.Column('crosstalk_warnings', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_reports_created_at'), 'verification_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_verification_reports_project_id'), 'verification_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_verification_reports_status'), 'verification_reports', ['status'], unique=False)
    op.create_table('versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versions_project_id'), 'versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_versions_tag'), 'versions', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_versions_tag'), table_name='versions')
    op.drop_index(op.f('ix_versions_project_id'), table_name='versions')
    op.drop_table('versions')
    op.drop_index(op.f('ix_verification_reports_status'), table_name='verification_reports')
    op.drop_index(op.f('ix_verification_reports_project_id'), table_name='verification_reports')
    op.drop_index(op.f('ix_verification_reports_created_at'), table_name='verification_reports')
    op.drop_table('verification_reports')
    op.drop_index(op.f('ix_tapeout_packages_version_tag'), table_name='tapeout_packages')
    op.drop_index(op.f('ix_tapeout_packages_project_id'), table_name='tapeout_packages')
    op.drop_table('tapeout_packages')
    op.drop_index(op.f('ix_simulations_status'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_project_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_created_at'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_qclang_files_project_id'), table_name='qclang_files')
    op.drop_table('qclang_files')
    op.drop_index(op.f('ix_layouts_project_id'), table_name='layouts')
    op.drop_table('layouts')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_project_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_created_at'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_projects_topology'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
