/** Qiskit Metal Python code generator. */
import type { ChipDocument } from "../model/document";
import { getComponent } from "../registry/registry";

export function generateQiskitMetal(doc: ChipDocument): string {
  const head = [
    `# Auto-generated by SilicoFeller Quantum Editor`,
    `# Design: ${doc.name}`,
    `from qiskit_metal import designs, MetalGUI`,
    `from qiskit_metal.qlibrary.qubits.transmon_cross import TransmonCross`,
    `from qiskit_metal.qlibrary.qubits.transmon_pocket import TransmonPocket`,
    `from qiskit_metal.qlibrary.qubits.transmon_pocket_cl import TransmonPocketCL`,
    `from qiskit_metal.qlibrary.qubits.transmon_concentric import TransmonConcentric`,
    `from qiskit_metal.qlibrary.tlines.meandered import RouteMeander`,
    `from qiskit_metal.qlibrary.tlines.straight_path import RouteStraight`,
    `from qiskit_metal.qlibrary.terminations.launchpad_wb import LaunchpadWirebond`,
    `from qiskit_metal.qlibrary.terminations.open_to_ground import OpenToGround`,
    `from qiskit_metal.qlibrary.terminations.short_to_ground import ShortToGround`,
    ``,
    `design = designs.DesignPlanar()`,
    `design.chips.main.size.size_x = "${doc.chipSize.w}mm"`,
    `design.chips.main.size.size_y = "${doc.chipSize.h}mm"`,
    ``,
  ];
  const body: string[] = [];
  for (const inst of doc.components) {
    const def = getComponent(inst.kind);
    if (!def) continue;
    body.push(...def.codegen(inst));
    body.push("");
  }
  const tail = [
    `# Netlist`,
  ];
  const byId = new Map(doc.components.map(c => [c.id, c]));
  for (const n of doc.nets) {
    const f = byId.get(n.from.component);
    const t = byId.get(n.to.component);
    if (f && t) {
      tail.push(`# ${f.name}.${n.from.pin} -> ${t.name}.${n.to.pin}`);
    }
  }
  tail.push(``, `gui = MetalGUI(design)`, `gui.rebuild()`);
  return [...head, ...body, ...tail].join("\n");
}
